<h1>Booking View Page</h1>
<?php $booking =$block->getBooking(); 
?>
<div> <b>First Name: </b> <span><?=$booking['firstname']?></span></div>
<div> <b>Last Name: </b> <span><?=$booking['lastname']?></span></div>
<div> <b>Email: </b> <span><?=$booking['email']?></span></div>
<div> <b>Telephone: </b> <span><?=$booking['telephone']?></span></div>
<div> <b>dob: </b> <span><?=$booking['dob']?></span></div>