<h1>Booking List</h1>
<div><?php $Bookings =$block->getBookings(); ?></div>

<?php if (count($Bookings) > 0): ?>
    <table border="1">
        <tr>
            <th><?= __("ID") ?></th>
            <th><?= __("Name") ?></th>
            <th><?= __("Email") ?></th>
            <th><?= __("View/Edit/Delete") ?></th>
        </tr>
        <?php foreach ($Bookings as $booking): ?>
            <tr>
                <td><?= $booking->getEntity_id() ?></td>
                <td><?= $booking->getFirstname() ." ".$booking->getLastname() ?></td>
                <td><?= $booking->getEmail() ?></td>
                <td><a href="<?= $block->getViewUrl()."id/".$booking->getEntity_id()?>">View</a>/<a href="<?= $block->getEditPageUrl()."id/".$booking->getEntity_id()?>">Edit </a>/<a href="<?= $block->getDeleteUrl()."id/".$booking->getEntity_id()?>">Delete </a></td><!-- todo Add the functionality of Edit and Delete booking -->
            </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <h1 style="color: red"><?= __("Bookings Not Available") ?></h1>
<?php endif; ?>